### PR TITLE
SUMO-164381: Adding Unescaped SDO FERs so user can copy/paste it dire…

### PR DESCRIPTION
**Pull request by ankitgoelcmu**
…ctly to sumo logic

### CODE REVIEW

**Comment by arunpatyal** [comment]
@ankitgoelcmu I think we can replace sdo_fer.json. I do not think json file is used anywhere else. Do you see a use case where it is used?

**Comment by ankitgoelcmu** [comment]
> @ankitgoelcmu I think we can replace sdo_fer.json. I do not think json file is used anywhere else. Do you see a use case where it is used?

I thought its been used by TF to create FERs. How do you create FERs by TF, where do you read it from ?

**Comment by arunpatyal** [comment]
That is a separate file. sumologic_fer.tf and sumologic_fer.auto.tfvars.

**Review by arunpatyal — APPROVED** [review]
LGTM

**Pull request merged**
